#!/bin/bash
pyinstaller --onefile ../spaceJam.py --add-binary="../res/GravityRobotBold8.ttf:res" --add-binary="../res/GravityRegular5.ttf:res" --add-binary="../res/rocket.png:res" --icon="rocket.ico"
